
# Generated by Django 6.0.6 on 2026-06-17 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=50)),
                ('nis', models.CharField(max_length=20)),
                ('status', models.CharField(default='Aktif', max_length=20)),
            ],
        ),
    ]

